- name: Create the users for the app files
  user: name={{ item.name }} groups=apache uid={{ item.user_id }} home={{ item.home | default ('/share/' + item.name) }} createhome=no append=yes
  with_items: php_fpm_apps

- name: Create the directories for the app files
  file: path={{ item.home | default ('/share/' + item.name) }} state=directory owner={{ item.name }} group={{ item.name }} mode=0755
  with_items: php_fpm_apps
